### ISSUE TITLE
Multiple autodiscounts only applies first discount.

### ISSUE THREAD

**Issue by kewljuice** [civicrm/org.civicrm.module.cividiscount#214] opened 2019-01-30 15:37 UTC
Case 'Events': 
- Auto discount based on membership (30%) for event type 'X'
- Auto discount based on membership and age >60 (50%) for event type 'X'

When trying to register for an event of type 'X', as current member and older than 60 only the first discount (30%) gets applied.

Case 'Membership'
- Auto discount based on age <100 (30%) for membership type 'X'
- Auto discount based on age <100 (50%) for membership type 'X'

When trying to register for a membership of type 'X', as logged in user with an age of 40 only the first discount (30%) gets applied.

**Comment by kewljuice** [comment] 2019-01-30 15:39
PR #210 does not solve my problem

**Comment by kewljuice** [comment] 2019-01-30 15:51
I've created a PR #215 to solve this issue

**Comment by JoeMurray** [comment] 2019-09-25 14:54
This is better understood as a feature request. It might be good to have a setting indicating what to do when multiple discounts could apply: multiply them, take the largest, take the smallest.

**Comment by colemanw** [comment] 2019-10-22 16:28
More discussion at https://lab.civicrm.org/extensions/cividiscount/issues/1

**Comment by MtnPavlas** [comment] 2020-02-05 08:23
I understand the need to further discuss any requirements around discount stacking.

However, I believe it is sound logic to apply the highest possible discount if multiple are applicable. At least, at the companies I've worked with/for over the years, we'd always err on the side of doing right by the customer (i.e. giving them the best possible deal).

Right now, the lowest ID discount trumps all other discounts ... since the admin user cannot change the discount ID, this makes no sense (i.e. "hey, as an admin, I'd be happy to rearrange which discount gets applied first, but guess what - I can't").

With this in mind, I'm hoping this patch can get accepted; it also solves #210 (which I created). Thank you for your consideration, guys!

**Comment by JoeMurray** [comment] 2020-02-05 14:25
In terms of requirements I am +1 for a change that applies maximum of applicable ones, and to treating this as a bit like a functionality implementation bug that it does not do it already. We should make this change in sustem behaviour is given appropriate prominence in release notes, @agh1.

**Comment by h-c-c** [comment] 2020-02-12 18:43
I agree @JoeMurray, this is better framed as a feature request. Something like: "Allow application of multiple auto-discounts".  I like how you've conceived the settings.  From this discussion there seems to be some belief that this was already a thing. https://lab.civicrm.org/extensions/cividiscount/issues/1    I don't believe that's true. 

I was going to ask that #215 be not merged because it's a regression on #167.  But from what I can tell, auto-discount tracking is not working at all now.  (sigh.)  Maybe someone else can confirm. 

Until we fix auto-discount tracking again, the difference between keeping the conditional break or not is: which matching auto-discount code is applied.  First or last.  

From what I understand some users want the highest value auto-discount be applied.  Even though end users can't change id numbers directly in the database, they truly do have control over what order the auto-discounts are created in.  If they want highest first, as a work around we can communicate that the first created auto-discount always wins.  

Until someone tackles a multiple auto-discounts feature, I think a stop gap measure is to just communicate to end users that the order matters.   The first created auto-discounts take precedence.

**Comment by agh1** [comment] 2020-02-12 19:07
I wonder if it would make sense to add a new weight field on the discount codes.  This would do two things:

- in the short run, the array of discounts could be restructured so it's ordered by weight.  The `foreach` could start with the lowest weight and quit after it hits an autodiscount
  https://github.com/civicrm/org.civicrm.module.cividiscount/blob/1b4eae48a009b6b834546cb4fa0671f4068c77ac/cividiscount.php#L369
  This would at least give the admin control over which discount applies.
- at a later point, if implemented, the discounts could be understood to stack in ascending weight order

**Comment by h-c-c** [comment] 2020-02-12 19:54
@MtnPavlas I just tried release 3.2 on Civi 5.19.1 because I saw your post here: https://github.com/civicrm/org.civicrm.module.cividiscount/issues/202#issue-347265916

I could not get multiple auto-discounts to apply to an event with matching membership criteria. Only one applies for me.

Assuming we're talking about the same thing, could you elaborate on your setup?  What civi version?  Can you describe how you're structuring the event fees?  With a price set or direct?    Thanks

**Comment by MtnPavlas** [comment] 2020-02-12 22:02
@h-c-c , only one discount (of multiple applicable) would get applied (which is fine - I do understand stacking is not available in CiviDiscount yet), but it's the one with the lowest ID vs. the highest value (again, this is up for debate which is better, but for customer-centric organizations, the latter is the way to go ... removing one line of code does just that, fortunately).

The problem issue #202 (and #210) describes is where a discount doesn't get applied if multiple discounts have been set up for the same event type, but different price set options.

Our setup:
- CiviDiscount 3.8.1 on CiviCRM 5.21.2 and Joomla 3.9.15
- Discounts (we have about 20 codes, but listing two for illustration):
- $20 off auto-discount on events of type "Class" for anyone with any current membership, applied to price set options A and B
- $35 off same as above, applied to price set options X, Y and Z

If a user registers for event of type "Class" w/ price set option X, the $35 discount doesn't get applied as the extension looks at the first discount in the table for event type "Class" (which is the $20 one), and stops there... even though in this case it's actually not applicable 'coz it doesn't apply to the price options used for this event, which is why I argue #202 is a bug - I filed it a year and a half ago so pardon my weak memory on all the details, but it's all pretty much listed in there, including the fact this worked just fine on CiviDiscount 3.2.

#210 and #215 (slightly different solutions) both solve this issue for me ... again, one line of code, but frustrating to remember to hack the file every time we upgrade CiviDiscount

**Comment by h-c-c** [comment] 2020-02-13 19:58
> @h-c-c , only one discount (of multiple applicable) would get applied (which is fine - I do understand stacking is not available in CiviDiscount yet), but it's the one with the lowest ID vs. the highest value (again, this is up for debate which is better, but for customer-centric organizations, the latter is the way to go ... removing one line of code does just that, fortunately).
> 

@MtnPavlas  I'm sorry, this is incorrect.  The only thing removing the `break`does, is take the highest matching id.  It has nothing do to with value size.  And how could it? Removing the `break` doesn't add any code with conditionals related to value.  It only _seems_ this way to you because you arbitrarily have the highest value as last matching auto-discount. It's at the at the end of your table.  To illustrate my point what you can do is create a lower value matching auto-discount and look at your event page again.  Please give it a go with the break removed.  I think you'll find that I'm right.  To sum it up.  It's not lowest id vs. highest value.  It's lowest id vs highest id. Right now, we can only communicate to end users how it functions.  To me, saying the auto-discounts at the top of the list take precedence.  AKA "First go first", which seems easiest to remember.  So this option is slightly better. 

I went ahead and made a screen cast to illustrate. 

[break-or-no-break.mov.zip](https://github.com/civicrm/org.civicrm.module.cividiscount/files/4200610/break-or-no-break.mov.zip)

That said, I did try the same setup with 3.2 and it 100% takes the largest value auto-discount. I changed the values of 3 different discounts.  Highest value always wins!   The break statement was not relevant here.  Apparently, there's a lot of diffing to do.  :/

> The problem issue #202 (and #210) describes is where a discount doesn't get applied if multiple discounts have been set up for the same event type, but different price set options.
> 
> Our setup:
> 
>     * CiviDiscount 3.8.1 on CiviCRM 5.21.2 and Joomla 3.9.15
> 
>     * Discounts (we have about 20 codes, but listing two for illustration):
> 
>     * $20 off auto-discount on events of type "Class" for anyone with any current membership, applied to price set options A and B
> 
>     * $35 off same as above, applied to price set options X, Y and Z
> 
> 
> If a user registers for event of type "Class" w/ price set option X, the $35 discount doesn't get applied as the extension looks at the first discount in the table for event type "Class" (which is the $20 one), and stops there... even though in this case it's actually not applicable 'coz it doesn't apply to the price options used for this event, which is why I argue #202 is a bug - I filed it a year and a half ago so pardon my weak memory on all the details, but it's all pretty much listed in there, including the fact this worked just fine on CiviDiscount 3.2.
> 
> #210 and #215 (slightly different solutions) both solve this issue for me ... again, one line of code, but frustrating to remember to hack the file every time we upgrade CiviDiscount

This is very interesting.  As I understand your setup, you are applying different discounts to different price-set options within the same price-set. Is that right? If so, how are you doing that?  With the advanced options? I'd need more info to reproduce this scenario.

**Comment by MtnPavlas** [comment] 2020-02-13 21:35
@h-c-c , our set up is multiple autodiscounts for the same event type, but _different field options_, each of which is in a _different price set_.

**Discount set-up example:**
1. Discount _eventmem20_: $20 off for current members for event type "Class" and price field option "Event Fee: $150" in price set A
2. Discount _eventmem35_: $35 off for current members for event type "Class" and price field option "Event Fee: $350" in price set B

**The way it works with CiviDiscount 3.3-3.8**
1. Event X w/ price set A: eventmem20 discount gets applied (GOOD)
2. Event Y w/ price set B: eventmem20 discount gets applied (BAD as we expect the eventmem35 discount)

**The way it works with CiviDiscount <3.3 or with fixes in #210 and #215 **
1. Event X w/ price set A: eventmem20 discount gets applied
2. Event Y w/ price set B: eventmem35 discount gets applied

So CiviDiscount grabs the first autodiscount for the applicable event type, and ignores the price field options completely - that's why I'm calling this a **bug**. We don't have overlapping discounts for any of our events (for event types, yes; but not for individual events).

Also, Jitendra originally solved this for us in #210, but I simply pointed out that #215 would also fix the way **we** set up our discounts.

Thanks for looking into this : )

**Comment by h-c-c** [comment] 2020-02-13 21:41
@MtnPavlas  Ok, how are you using 2 different price sets in the same event?

**Comment by MtnPavlas** [comment] 2020-02-13 22:54
@h-c-c I'm not

**Comment by mlutfy** [comment] 2021-09-14 13:30
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/214

**Closed by mlutfy** 2021-09-14 13:30 UTC
